--
-- PostgreSQL database dump
--

\restrict zHXnsAHLHpcmJoQmFf5oJufhjdkCHh3vPk8Ca5kIWbW862fDQOmnpyqBErtRJR0

-- Dumped from database version 17.11 (Homebrew)
-- Dumped by pg_dump version 17.11 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id bigint NOT NULL,
    device_id integer NOT NULL,
    interface_index integer,
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    severity text NOT NULL,
    event_type text NOT NULL,
    source text NOT NULL,
    message text NOT NULL,
    CONSTRAINT events_severity_check CHECK ((severity = ANY (ARRAY['info'::text, 'warning'::text, 'error'::text, 'critical'::text]))),
    CONSTRAINT events_source_check CHECK ((source = ANY (ARRAY['snmp_poll'::text, 'snmp_trap'::text, 'syslog'::text, 'system'::text])))
);


--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: managed_devices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.managed_devices (
    id integer NOT NULL,
    management_ip inet NOT NULL,
    device_type text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    snmp_port integer DEFAULT 161 NOT NULL,
    snmp_version text NOT NULL,
    CONSTRAINT managed_devices_device_type_check CHECK ((device_type = ANY (ARRAY['router'::text, 'switch'::text, 'server'::text, 'client'::text]))),
    CONSTRAINT managed_devices_snmp_port_check CHECK (((snmp_port >= 1) AND (snmp_port <= 65535))),
    CONSTRAINT managed_devices_snmp_version_check CHECK ((snmp_version = ANY (ARRAY['v2c'::text, 'v3'::text])))
);


--
-- Name: managed_devices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.managed_devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.managed_devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: snmp_interfaces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.snmp_interfaces (
    device_id integer NOT NULL,
    if_index integer NOT NULL,
    description text,
    interface_type integer,
    mtu integer,
    speed bigint,
    mac_address macaddr,
    admin_status integer,
    oper_status integer
);


--
-- Name: snmp_ip_addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.snmp_ip_addresses (
    device_id integer NOT NULL,
    interface_index integer NOT NULL,
    address inet NOT NULL,
    subnet_mask inet
);


--
-- Name: snmp_routes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.snmp_routes (
    device_id integer NOT NULL,
    interface_index integer NOT NULL,
    destination inet NOT NULL,
    subnet_mask inet NOT NULL,
    next_hop inet NOT NULL,
    route_type integer,
    protocol integer,
    age integer
);


--
-- Name: snmp_system; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.snmp_system (
    device_id integer NOT NULL,
    description text,
    object_id text,
    uptime bigint,
    name text,
    location text
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    username text NOT NULL,
    password_hash text NOT NULL,
    role text NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: managed_devices managed_devices_management_ip_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.managed_devices
    ADD CONSTRAINT managed_devices_management_ip_key UNIQUE (management_ip);


--
-- Name: managed_devices managed_devices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.managed_devices
    ADD CONSTRAINT managed_devices_pkey PRIMARY KEY (id);


--
-- Name: snmp_interfaces snmp_interfaces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snmp_interfaces
    ADD CONSTRAINT snmp_interfaces_pkey PRIMARY KEY (device_id, if_index);


--
-- Name: snmp_ip_addresses snmp_ip_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snmp_ip_addresses
    ADD CONSTRAINT snmp_ip_addresses_pkey PRIMARY KEY (device_id, interface_index, address);


--
-- Name: snmp_routes snmp_routes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snmp_routes
    ADD CONSTRAINT snmp_routes_pkey PRIMARY KEY (device_id, destination, subnet_mask, next_hop);


--
-- Name: snmp_system snmp_system_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snmp_system
    ADD CONSTRAINT snmp_system_pkey PRIMARY KEY (device_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: events events_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.managed_devices(id) ON DELETE CASCADE;


--
-- Name: snmp_interfaces snmp_interfaces_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snmp_interfaces
    ADD CONSTRAINT snmp_interfaces_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.managed_devices(id) ON DELETE CASCADE;


--
-- Name: snmp_ip_addresses snmp_ip_addresses_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snmp_ip_addresses
    ADD CONSTRAINT snmp_ip_addresses_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.managed_devices(id) ON DELETE CASCADE;


--
-- Name: snmp_ip_addresses snmp_ip_addresses_interface_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snmp_ip_addresses
    ADD CONSTRAINT snmp_ip_addresses_interface_fkey FOREIGN KEY (device_id, interface_index) REFERENCES public.snmp_interfaces(device_id, if_index) ON DELETE CASCADE;


--
-- Name: snmp_routes snmp_routes_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snmp_routes
    ADD CONSTRAINT snmp_routes_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.managed_devices(id) ON DELETE CASCADE;


--
-- Name: snmp_routes snmp_routes_interface_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snmp_routes
    ADD CONSTRAINT snmp_routes_interface_fkey FOREIGN KEY (device_id, interface_index) REFERENCES public.snmp_interfaces(device_id, if_index) ON DELETE CASCADE;


--
-- Name: snmp_system snmp_system_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.snmp_system
    ADD CONSTRAINT snmp_system_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.managed_devices(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict zHXnsAHLHpcmJoQmFf5oJufhjdkCHh3vPk8Ca5kIWbW862fDQOmnpyqBErtRJR0

